package com.info.back.dao;


import com.info.back.pojo.BackDistributeRecord;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;

/**
 * 派单操作记录dao
 *
 * @author：tgy
 */
@Repository
public interface IBackDistributeRecordDao {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database
     * table back_ditribute_record
     *
     * @mbg.generated Thu Aug 09 15:43:05 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database
     * table back_ditribute_record
     *
     * @mbg.generated Thu Aug 09 15:43:05 CST 2018
     */
    int insert(BackDistributeRecord record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database
     * table back_ditribute_record
     *
     * @mbg.generated Thu Aug 09 15:43:05 CST 2018
     */
    int insertSelective(BackDistributeRecord record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database
     * table back_ditribute_record
     *
     * @mbg.generated Thu Aug 09 15:43:05 CST 2018
     */
    BackDistributeRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database
     * table back_ditribute_record
     *
     * @mbg.generated Thu Aug 09 15:43:05 CST 2018
     */
    int updateByPrimaryKeySelective(BackDistributeRecord record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database
     * table back_ditribute_record
     *
     * @mbg.generated Thu Aug 09 15:43:05 CST 2018
     */
    int updateByPrimaryKey(BackDistributeRecord record);

    List<BackDistributeRecord> findParams(Map<String, Object> params);

    int findParamsCount(Map<String, Object> params);

}